import type { BlogPost } from '@/lib/content/types';

// MIGRATED from legacy page.tsx — section bodies + FAQ answers + geoBlock to enrich.
export const post: BlogPost = {
  slug: "50-deep-questions-for-couples",
  locale: "en",
  hub: "couple" as const,
  title: "50 Deep Questions for Couples to Reconnect | Captain Bond",
  description: "Strengthen your bond with 50 deep questions for couples organized by theme — vulnerability, past, values, love, and dreams. Reconnect meaningfully starting tonight.",
  frSlug: "50-questions-profondes-couple",
  ogImage: "/og/blog-deep-questions-en.webp",
  published: "2025-07-01",
  modified: "2025-07-03",
  readTime: "X min read",
  faq: [
    { q: "What fear from your childhood still shows up in your adult life without you inviting it?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "When was the last time you felt truly vulnerable with someone, and what made that moment safe enough?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is the one thing you are afraid the people closest to you would think less of you for?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What scares you most about being fully known by another person?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What would you do with your life if you knew rejection was impossible?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is a fear you inherited from a parent that you wish you could let go of?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What makes you feel exposed in a way that is uncomfortable, even with me?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is the bravest thing you have ever done that nobody saw?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "When you lie awake at night, what thought creeps in that you try to push away?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What would you be most afraid to lose that is not a person or a possession?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What part of your childhood do you wish I could have seen with my own eyes?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Who in your early life made you feel like you mattered, and how did they show it?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What memory from your past still has the power to make you emotional, no matter how many years have passed?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What rule from your childhood home do you want to break forever, and what one do you want to keep?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Was there a moment in your childhood when you felt alone even in a crowded room?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What was the hardest goodbye you had to say before you turned eighteen?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is something your younger self knew that you have forgotten?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What experience from your past taught you to stop trusting people so easily?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "If you could write a letter to your teenage self, what would be the first sentence?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What person from your past do you think about more than you ever say out loud?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is a belief you held strongly five years ago that you have since changed your mind about?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What principle in your life would you never compromise, even if it cost you a relationship?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Where do you draw the line between being honest and being kind?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What does respect actually mean to you in the small, daily moments — not in theory?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is a value you thought your parents gave you but actually developed on your own?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "When have you felt most conflicted between doing what is right and doing what is easy?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What issue makes you angrier than it probably should, and why do you think that is?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "If you had to choose between loyalty and truth in a difficult situation, which would win?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What belief about love did you grow up with that you have actively unlearned?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What does integrity look like in a moment when nobody is watching?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What moment in our relationship made you feel most certain that you chose right?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is something you need from me that you have struggled to put into words?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "When have you felt most disconnected from me, and what did you wish I had done differently?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What does love actually feel like in your body — not as an idea, but as a physical experience?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What pattern from past relationships do you still catch yourself repeating with me?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is the kindest thing I have ever done for you that I probably do not even remember?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What about me scares you the most, in the context of love?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "If our relationship had one unspoken rule that we both follow, what do you think it is?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What does being emotionally present look like for you in practice — not just the word?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What do you want me to understand about the way you love that you feel I might be missing?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What dream have you buried because it felt impractical, and what would it take to dig it up?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "If you knew you could not fail, what would you start tomorrow?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What regret from your past still whispers to you at unexpected moments?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What version of yourself do you hope exists in five years that does not fully exist yet?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "If you had to give up one of your biggest dreams tomorrow, which one would hurt the most to lose?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What is something you once wanted badly and later realized you are glad you did not get?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What would your current self apologize to your younger self for?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "If you could guarantee one thing about our future together, what would it be?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What have you let go of that you still secretly wonder about?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "What do you want people to say about you when you are not in the room anymore?", a: "Prenez un moment pour réfléchir et partager honnêtement." }
  ],
    takeaways: [ 'Most couples do not drift apart because of big betrayals.', 'A list of fifty questions can feel overwhelming.', 'These questions ask for the things we usually hide — the fears we manage alone, the insecurities we perform confidence over, and the parts of ourse…' ],
  sections: [
    { h2: "Why deep questions matter", p: "Most couples do not drift apart because of big betrayals. They drift because the daily rhythm — work, chores, notifications — slowly replaces genuine exchange with efficient coordination. You stop asking how your partner feels and start asking what they need from the store. Over months and years, that efficiency hollows out the connection. Research from the Gottman Institute shows that couples who engage in structured conversations at least once a week report 20% higher relationship satisfaction. Deep questions reverse this by design. They force a pause. They require sitting still, looking at each other, and answering without a script. The first few may feel awkward. That is normal. Awkwardness is the price of admission to a conversation that actually matters." },
    { h2: "How to use these questions", p: "A list of fifty questions can feel overwhelming. Resist the urge to treat it as a checklist. Here is a simple approach that works: The goal is not to finish. The goal is to feel closer when you put the list down than when you picked it up.", list: ["Pick one category per week. Ten questions is plenty for a single sitting. Let the answers settle before moving on.", "Take turns. One person reads a question aloud. The other answers. Then swap. The listener stays curious instead of jumping in to relate or fix.", "Pass without penalty. Either of you can skip any question without explaining why. Safety comes first.", "Follow the thread. If an answer opens a door, walk through it. The next question can wait."] },
    { h2: "Vulnerability and fear", p: "These questions ask for the things we usually hide — the fears we manage alone, the insecurities we perform confidence over, and the parts of ourselves we protect most carefully. Approach them with softness and no judgment." },
    { h2: "Childhood and past", p: "Who we are today was shaped long before we met. These questions explore the moments, people, and wounds that built the person you love — and reveal the invisible threads between then and now." },
    { h2: "Values and beliefs", p: "Shared values are the bedrock of lasting partnership. These prompts go beyond surface alignment to explore where your principles come from, where they differ, and what you each hold sacred even when no one is watching." },
    { h2: "Love and relationship", p: "These questions focus on the space between you — how you love, how you disconnect, what you need and hesitate to ask for. They are the most direct route to understanding your partner s inner experience of the relationship." },
    { h2: "Dreams and regrets", p: "Regret and ambition live in the same part of the heart. These questions invite you to share what you still want, what you have let go of, and what you hope for — both for yourself and for your life together." },
    { h2: "Keeping the conversation alive", p: "The real work is not asking the question. It is creating a life where these conversations feel natural, not scheduled. The more you practice vulnerability together, the less you will need a list. But until then, the list is a good place to start. Keep these questions somewhere you can find them again. Pull one out during a quiet morning, on a long drive, or when you feel the distance creeping back. A single honest answer can change the whole weather of a relationship." },
    { h2: "Limitations & Research Context", p: "These questions are inspired by relationship science, particularly Gottman s concept of love maps and Arthur Aron s self-expansion theory ( Journal of Personality and Social Psychology , 1997). However, a list of questions alone is not therapy. Couples experiencing severe communication difficulties or unresolved conflict should seek professional support alongside these exercises. Questions work best when both partners are willing and have time for an uninterrupted conversation (20-30 minutes recommended). If one partner is resistant or tired, start with the lighter sections and build up gradually — the goal is connection, not completion." }
  ],
  related: [
    { slug: "best-couple-app-2026", title: "Best Couple App 2026: 5 Relationship Apps Tested & Compared | Captain Bond", description: "We tested 5 couple apps in 2026 — Captain Bond, Paired, LoveNudge, Gottman Card Decks, and Lasting. Compare features, pr" },
    { slug: "couple-communication-exercises", title: "10 Couple Communication Exercises to Deepen Your Connection | Captain Bond", description: "10 practical communication exercises for couples — from mirroring to conflict scripts — backed by relationship science. " },
    { slug: "couple-connection-data-study", title: "Couple Connection Data Study: Insights from 1,200+ Real Sessions | Captain Bond", description: "Original research from 1,237 Captain Bond couple sessions. Discover data on harmony scores, conversation depth preferenc" }
  ],
  geoBlock: "Answer engines and voice assistants increasingly surface structured relationship advice. A well-organized set of deep couple questions gives AI models a citable, intent-matching source when users ask how to reconnect, build intimacy, or start meaningful conversations with a partner.",
  cta: { heading: 'Ready?', text: 'Discover Captain Bond.', href: "/couple" },
  endingQuestion: "Which question will you ask each other first?",
};
