import type { BlogPost } from '@/lib/content/types';

// MIGRATED from legacy page.tsx — section bodies + FAQ answers + geoBlock to enrich.
export const post: BlogPost = {
  slug: "50-questions-profondes-couple",
  locale: "fr",
  hub: "couple" as const,
  title: "50 questions profondes pour couple : se reconnecter | Captain Bond",
  description: "Retrouvez une complicité durable avec 50 questions profondes pour couple en français. Vulnérabilité, passé, valeurs, amour et rêves — pour des soirées qui rapprochent.",
  frSlug: "50-deep-questions-for-couples",
  ogImage: "/og/blog-deep-questions-fr.webp",
  published: "2025-07-01",
  modified: "2025-07-03",
  readTime: "X min de lecture",
  faq: [
    { q: "De quoi as-tu le plus peur que je pense de toi sans jamais oser me le dire ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quand as-tu pleuré pour la dernière fois, et qu'est-ce qui a libéré cette émotion ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle partie de toi caches-tu par habitude, même quand personne ne te juge ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce qui te rend plus vulnérable que tu ne le laisses paraître ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si tu pouvais supprimer une insécurité d'un claquement de doigts, laquelle disparaîtrait ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quand te sens-tu le plus seul, même en étant accompagné ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel mensonge banal as-tu déjà raconté pour éviter de montrer ta fragilité ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu redoutes le plus dans l'idée d'être vraiment connu de moi ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "À quel moment as-tu eu honte d'une réaction que tu n'as pas su contrôler ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que la peur t'a empêché de vivre pleinement cette année ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel objet de ton enfance gardes-tu encore et que personne ne connaît ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel souvenir d'école te rend encore triste aujourd'hui ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle personne de ton enfance a changé le cours de ta vie sans le savoir ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle injustice subie enfant n'est toujours pas réparée dans ton cœur ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si tu pouvais revivre un seul été de ton passé, lequel choisirais-tu ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle phrase entendue petit te trotte encore dans la tête ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel rêve d'enfant as-tu abandonné trop tôt ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel moment avec tes parents aimerais-tu revivre une dernière fois ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Y a-t-il un lieu de ton enfance qui n'existe plus et que tu portes en toi ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel meilleur souvenir de toi enfant aimerais-tu que je connaisse ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce qui est plus important pour toi que notre relation, et pourquoi ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Sur quel sujet es-tu intransigeant même avec ceux que tu aimes ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle valeur défendrais-tu coûte que coûte, quitte à perdre des amis ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Où places-tu la limite entre l'honnêteté et la bienveillance ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que l'échec représente pour toi — vraiment — pas la définition des autres ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Dans quelle situation as-tu trahi une de tes propres valeurs par peur du conflit ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu admires chez les autres et que tu n'arrives pas à incarner toi-même ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle croyance sur l'argent t'empêche d'avancer ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si tu devais choisir entre être heureux et avoir raison, que choisirais-tu ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce qui mérite de se battre aujourd'hui dans le monde, selon toi ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel petit geste de mon côté te fait sentir aimé sans qu'un mot soit dit ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quand as-tu douté de notre histoire pour la première fois ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu n'oses pas me demander, de peur de ma réaction ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Dans quel moment de notre vie commune t'es-tu senti invisible ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu aimes chez moi que je n'aime pas chez moi-même ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel besoin émotionnel as-tu l'impression de devoir combler seul ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu voudrais que je comprenne de ta façon d'aimer, que tu n'arrives pas à m'expliquer ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel reproche retiens-tu parce que tu trouves que ce serait injuste de le formuler ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Dans quel domaine de notre couple as-tu l'impression de faire tous les efforts ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce qui te rassurerait sur notre avenir si je te le disais aujourd'hui ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si la peur et l'argent n'existaient pas, quelle vie mènerais-tu demain ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel rêve as-tu rangé dans un tiroir et que tu n'as jamais osé sortir ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu regretterais à 80 ans de ne pas avoir tenté ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si tu pouvais changer un seul choix de ton passé, lequel serait-ce ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Où te vois-tu dans cinq ans si tout va bien — et si tout va mal ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel projet secret gardes-tu parce que tu crains qu'on le trouve ridicule ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu espères pour nous dans dix ans, que tu n'oses pas formuler à voix haute ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel talent as-tu laissé mourir faute de temps ou de courage ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si notre histoire était un livre, que voudrais-tu écrire dans le prochain chapitre ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle trace veux-tu laisser dans ce monde, même petite ?", a: "Prenez un moment pour réfléchir et partager honnêtement." }
  ],
  takeaways: [
    'TODO takeaway 1', 'TODO takeaway 2', 'TODO takeaway 3'
  ],
  sections: [
    { h2: "Pourquoi les questions profondes sont essentielles", p: "La plupart des couples ne s éloignent pas à cause d une trahison fracassante. Ils s éloignent parce que le rythme du quotidien — le travail, les courses, les écrans — remplace peu à peu l échange authentique par une coordination efficace. On cesse de demander comment l autre se sent pour demander ce qu il faut acheter au supermarché. Avec les mois, cette efficacité creuse un vide. Selon une étude du Gottman Institute, les couples qui ont des conversations structurées au moins une fois par semaine rapportent 20 % de satisfaction relationnelle en plus. Les questions profondes inversent ce mécanisme. Elles imposent une pause. Elles obligent à s asseoir, à se regarder, à répondre sans filet. Les premières seront peut-être gênantes. C est normal. La gêne est le prix d entrée d une conversation qui compte vraiment." },
    { h2: "Comment utiliser ces questions", p: "Une liste de cinquante questions peut sembler intimidante. Résistez à l envie d en faire une check-list. Voici une approche simple qui fonctionne : Le but n est pas de finir la liste. Le but est de se sentir plus proches en la posant qu en la prenant.", list: ["Une catégorie par semaine. Dix questions suffisent pour une soirée. Laissez les réponses infuser avant de passer à la suite.", "Alternez. Une personne lit la question à voix haute. L autre répond. Puis on échange. Celui qui écoute reste curieux sans chercher à relativiser ou à résoudre.", "Passez sans pénalité. Chacun peut sauter une question sans s expliquer. La sécurité passe avant tout.", "Suivez le fil. Si une réponse ouvre une porte, entrez. La question suivante attendra."] },
    { h2: "Vulnérabilité et peur", p: "Ces questions explorent ce que nous cachons d habitude — les peurs qu on gère seul, les insécurités qu on maquille en confiance, les parties de nous qu on protège le plus farouchement. Abordez-les avec douceur et sans jugement." },
    { h2: "Enfance et passé", p: "Ce que nous sommes aujourd hui s est construit bien avant notre rencontre. Ces questions remontent le fil des souvenirs, des personnes et des blessures qui ont façonné la personne que vous aimez — et révèlent les liens invisibles entre hier et aujourd hui." },
    { h2: "Valeurs et croyances", p: "Les valeurs partagées sont le socle d une relation durable. Ces questions vont au-delà des convergences de surface pour explorer d où viennent vos principes, où ils divergent, et ce que chacun tient pour sacré — même quand personne ne regarde." },
    { h2: "Amour et relation", p: "Ces questions se concentrent sur l espace entre vous — comment vous aimez, comment vous vous déconnectez, ce dont vous avez besoin et que vous hésitez à demander. C est le chemin le plus direct vers la compréhension intime de l autre." },
    { h2: "Rêves et regrets", p: "Le regret et l ambition habitent la même chambre du cœur. Ces questions vous invitent à partager ce que vous voulez encore, ce que vous avez laissé tomber et ce que vous espérez — pour vous-même et pour votre vie à deux." },
    { h2: "Garder la conversation vivante", p: "Le vrai travail n est pas de poser la question. C est de construire une vie où ces conversations deviennent naturelles, pas programmées. Plus vous pratiquez la vulnérabilité à deux, moins vous aurez besoin d une liste. Mais en attendant, la liste est un bon point de départ. Gardez ces questions à portée de main. Sortez-en une pendant un petit-déjeuner tranquille, sur la route d un week-end ou quand vous sentez la distance revenir. Une seule réponse honnête peut changer tout le climat d une relation." }
  ],
  related: [
    { slug: "etude-donnees-connexion-couple", title: "Étude données connexion couple : 1 200+ sessions analysées | Captain Bond", description: "Analyse de 1 237 sessions Captain Bond : scores d'harmonie, préférences de questions, moments clés pour la connexion. Do" },
    { slug: "exercices-communication-couple", title: "10 exercices de communication pour couple : renforcez votre lien | Captain Bond", description: "10 exercices de communication pratiques pour les couples — du mirroring aux scripts de conflit — validés par la science " },
    { slug: "meilleure-application-couple-2026", title: "Meilleure application couple 2026 : 5 applis testées & comparées | Captain Bond", description: "Nous avons testé 5 applications couple en 2026 — Captain Bond, Paired, LoveNudge, Gottman Card Decks et Lasting. Compare" }
  ],
  geoBlock: "Les moteurs de réponse et assistants vocaux renvoient de plus en plus de conseils relationnels structurés. Un jeu de questions profondes bien organisé offre aux IA une source citable quand on demande comment se reconnecter ou approfondir avec son partenaire.",
  cta: { heading: 'Ready?', text: 'Discover Captain Bond.', href: "/couple" },
  endingQuestion: "Quelle question vous poserez-vous en premier ?",
};
