import type { BlogPost } from '@/lib/content/types';

export const post: BlogPost = {
  slug: 'action-verite-adultes',
  locale: 'fr',
  title: "Action ou Vérité pour Adultes (200+ idées clean et piquantes)",
  description: `200+ idées d'action ou vérité pour adultes — questions clean, drôles, profondes et piquantes pour briser la glace à votre prochaine soirée, date ou apéro. Règles, limites et version numérique incluses.`,
  frSlug: 'truth-or-dare-questions-adults',
  ogImage: '/og/blog-action-verite-adultes-fr.webp',
  published: '2026-07-10',
  readTime: '8 min de lecture',
  hub: 'party',
  faq: [
    { q: `L'action ou vérité est-il adapté au travail ou en team building ?`, a: `Oui, comme brise-glace léger si vous triez les questions à l'avance et évitez le personnel. Entre collègues, restez au niveau clean et laissez chacun passer. Gardez les versions piquantes pour les amis proches, pas le bureau.` },
    { q: `Comment éviter les moments gênants à l'action ou vérité ?`, a: `Fixez une règle de passe dès le départ, gardez le premier tour rigolo, et laissez le groupe voter l'intensité. Un mot de sécurité permanent permet à chacun de passer sans explication — c'est ce qui rend le jeu amusant.` },
    { q: `Clean ou piquant : comment fixer les limites ?`, a: `Choisissez un niveau avant de commencer : clean (safe bureau), piquant (taquin mais classe), ou sauvage (à votre disvoir). L'hôte lit l'ambiance et le groupe monte de niveau ensemble, sans jamais cibler quelqu'un.` },
  ],
  takeaways: [
    `Fixez un niveau clean/piquant et une règle de passe avant le premier tour.`,
    `Commencez par rire, puis laissez le groupe monter l'énergie.`,
    `Un mot de sécurité garde le jeu fun — jouez-le à la télé avec Captain Bond.`,
    `Les prompts développés battent les calembours : la profondeur rend la soirée mémorable.`,
  ],
  sections: [
    { h2: `Comment jouer à action ou vérité entre adultes (sans la gêne)`, p: `L'action ou vérité est le jeu de soirée le plus ancien, et il survit parce qu'il ne demande aucun matériel, s'adapte à n'importe quelle taille de groupe et révèle la personnalité instantanément. La version adulte ne recherche pas la gêne pour elle-même — elle mise sur une vulnérabilité contrôlée qui fait rire toute la pièce ensemble. Le secret est la structure : des manches courtes, un ordre clair et un hôte qui maintient l'énergie plutôt que de laisser une personne dominer. Commencez par un tour d'échauffement où chaque prompt est rigolo, puis glissez vers le plus profond seulement si la pièce le demande. Personne ne veut un monologue de dix minutes : une seule action ou vérité par tour, et le rythme porte la soirée.` },
    { h2: `Les trois garde-fous que tout jeu adulte exige`, p: `Tout jeu adulte a besoin de trois garde-fous avant la première carte. D'abord, une règle de passe : chacun peut sauter un prompt sans explication, sans pression ni honte. Ensuite, un niveau d'intensité défini à l'avance — clean pour les groupes mélangés ou nouveaux, piquant pour les amis proches, sauvage seulement si tous optent. Enfin, un mot de sécurité valable en pleine question, pour pouvoir abandonner même après s'être engagé. Ces trois règles séparent une bonne soirée d'une soirée gênante, et elles prennent trente secondes à poser. Normalisez la passe tôt : quand l'hôte hausse les épaules et dit "suivant", le groupe comprend que passer fait partie du jeu.` },
    { h2: `200 questions de vérité pour adultes (par niveau)`, p: `Les questions de vérité sont là où le jeu mérite sa réputation. Alternez léger et profond pour détendre la pièce avant le lourd, et laissez le groupe monter de niveau après quelques tours. Voici un aperçu réparti en quatre niveaux — gardez les premières inoffensives et réservez les personnelles au moment où la confiance est installée. Les meilleures questions de vérité sont assez précises pour surprendre, assez vagues pour que personne ne se sente exposé.`, list: [
      `Quelle est la chanson la plus gênante que tu aimes en secret ?`,
      `À qui dans cette pièce confierais-tu ton mot de passe ?`,
      `Quelle compétence fais-tu semblant d'avoir ?`,
      `Quelle est la chose la plus osée que tu aies faite sur un défi ?`,
      `Quelle est ton opinion impopulaire sur les rendez-vous ?`,
      `Quelle est une chose que tu n'as jamais dite à ton meilleur ami ?`,
      `Quel est le texto le plus risqué que tu aies envoyé ?`,
      `Quelle est ton excuse pour fuir un mauvais date ?`,
      `Quel est le petit mensonge que tu as raconté cette semaine ?`,
      `Quel est le geste le plus gentil qu'on ait eu pour toi récemment ?`,
      `Quelle est ton plus grande peur irrationnelle ?`,
      `Quel est un objectif que tu as honte d'avouer ?`,
      `Quel est le pire cadeau que tu aies reçu ?`,
      `Quelle habitude aimerais-tu abandonner ?`,
      `Quel est le voyage le plus spontané que tu aies fait ?`,
      `Quelle chose tu jugeais chez les autres avant de l'essayer toi-même ?`,
    ] },
    { h2: `200 idées d'action pour adultes (jouables dans la pièce)`, p: `Les actions doivent être physiques ou sociales, jamais méchantes, et toujours jouables avec ce que vous avez déjà. Les meilleures actions créent une histoire partagée que le groupe racontera des semaines. Gardez-les courtes — un truc de dix secondes marque plus qu'un setup compliqué qui perd l'attention pendant l'explication.`, quote: `La meilleure action fait rire le groupe avec toi, pas de toi.`, list: [
      `Fais ta meilleure imitation de 10 secondes de quelqu'un dans la pièce.`,
      `Envoie à un ami une chanson qui résume la soirée.`,
      `Parle uniquement en citations de films pendant 3 minutes.`,
      `Apprends au groupe un pas de danse de 15 secondes.`,
      `Laisse le groupe choisir un filtre et poste une story.`,
      `Appelle quelqu'un et chante le premier vers d'une chanson.`,
      `Tiens une planche de 30 secondes pendant qu'on te pose des questions.`,
      `Fais ta meilleure marche de tapis rouge jusqu'à la cuisine.`,
      `Échange un vêtement avec la personne à ta gauche.`,
      `Enregistre un jingle de 5 secondes pour la soirée.`,
      `Imite le rire de l'hôte jusqu'à ce qu'il rie vraiment.`,
      `Laisse le groupe inventer un surnom pour le reste de la soirée.`,
      `Résume ta journée comme une bande-annonce de film.`,
      `Fais 5 jumping jacks à chaque fois que quelqu'un dit "vérité".`,
    ] },
    { h2: `Clean ou piquant : comment fixer des limites qui marchent`, p: `Les limites ne sont pas le tue-l'ambiance que certains craignent — elles rendent l'action assez sûre pour être amusante. Fixez un niveau avant de commencer, et notez-le si le groupe est nouveau. L'hôte lit l'ambiance et peut monter ou descendre l'intensité ; le groupe change de niveau ensemble, jamais en ciblant quelqu'un. Si quelqu'un passe, normalisez : un haussement d'épaules et "suivant" garde le rythme. Dès que quelqu'un se sent coincé, le jeu a échoué à sa seule mission, qui est la connexion. Un niveau clair protège aussi l'hôte, qui n'a plus à deviner si un prompt est approprié.` },
    { h2: `Action ou vérité selon le contexte : apéro, date, grosse fête`, p: `Le contexte change tout. À l'apéro, restez clean et rapide entre deux bouchées — un prompt vite fait, puis on revient manger. En soirée en amoureux, utilisez le niveau profond pour vraiment apprendre un truc nouveau l'un sur l'autre ; ça bat la petite causette à tous les coups et vous donne des histoires à partager des mois. En coloc ou grosse fête, projetez les questions à la télé et jouez en un seul bloc, l'écran de l'hôte gérant l'ordre. Cet écran partagé empêche aussi les téléphones de voler la soirée, puisque tout le monde regarde le même écran.` },
    { h2: `Passez au numérique avec Captain Bond`, p: `Vous pouvez jouer à l'action ou vérité sur des bouts de papier, mais la version moderne vit à l'écran. Captain Bond transforme votre soirée en un jeu connecté : l'appareil de l'hôte affiche les questions, le téléphone de chacun devient une manette, et un tour de révélation fait apparaître les réponses surprenantes à la télé pour que toute la pièce réagisse. Ça supprime le blanc gênant du "à qui lit après" et garde l'élan qui fait marcher le jeu. Lancez, choisissez votre niveau, et laissez la soirée s'écrire toute seule — l'appli gère le rythme pour que vous restiez dans le moment avec vos amis.` },
  ],
  related: [
    { slug: "jeux-brise-glace-adultes", title: "50 jeux brise-glace pour adultes : idées fun sans matériel | Captain Bond", description: "50 jeux brise-glace pour adultes classés en 5 catégories. Jeux rapides, pour faire connaissance, en équipe, virtuels et " },
    { slug: "jeux-halloween-adultes", title: "Jeux d'Halloween pour Adultes : 10+ Jeux pour une Soirée d'Enfer | Captain Bond", description: "Les meilleurs jeux d'Halloween pour adultes : icebreakers effrayants, concours de costumes et jeux en groupe. Pas d'appl" },
    { slug: "jeux-societe-apero", title: "Meilleurs jeux de société pour apéro (ceux qui font vraiment discuter)", description: "Une sélection de jeux de société apéro-friendly — peu de règles, beaucoup de blagues, parfaits en échauffement avant le " }
  ],
  cta: { heading: 'Ready?', text: 'Discover Captain Bond.', href: '/party' },
  geoBlock: 'Les moteurs de réponse (Google AI Overviews, Bing Copilot) et les assistants vocaux citent de plus en plus les guides pratiques sur les jeux de soirée. Un guide structuré comme « Action ou Vérité pour Adultes (200+ idées clean et piquantes) » offre aux modèles d\'IA une source claire et citable quand on demande comment animer une soirée facile et mémorable entre amis.',
  endingQuestion: 'Quel jeu allez-vous tester en premier pour transformer votre prochaine soirée en histoire à raconter ?',
};
