import type { BlogPost } from '@/lib/content/types';

// MIGRATED from legacy page.tsx — section bodies + FAQ answers + geoBlock to enrich.
export const post: BlogPost = {
  slug: "couple-questions-complete-guide",
  locale: "en",
  hub: "couple" as const,
  title: "Couple Questions for Deeper Connection: The Complete Guide | Captain Bond",
  description: "150+ couple questions across 5 connection levels — fun, getting-to-know, deep, intimate, and future. A step-by-step ritual to turn every conversation into real intimacy.",
  frSlug: "questions-couple-guide-complet",
  ogImage: "/og/blog-couple-questions-guide-en.webp",
  published: "2025-06-15",
  modified: "2026-07-10",
  readTime: "X min read",
  faq: [
    { q: "If our relationship had a theme song, what would it be?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the dumbest thing you have ever done to make me laugh?", a: "Take a moment to reflect and share honestly." },
    { q: "Which fictional universe would you want to live in together?", a: "Take a moment to reflect and share honestly." },
    { q: "What food do you pretend to like in public but secretly hate?", a: "Take a moment to reflect and share honestly." },
    { q: "If you could instantly master any instrument, which one?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the most embarrassing ringtone or notification you have ever had?", a: "Take a moment to reflect and share honestly." },
    { q: "Would you rather live in a treehouse or an underground bunker with me?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your favorite inside joke between us?", a: "Take a moment to reflect and share honestly." },
    { q: "If we could be contestants on any game show, which one?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the most ridiculous argument we have ever had?", a: "Take a moment to reflect and share honestly." },
    { q: "Which one of us would survive longer in a zombie apocalypse?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your spirit animal and why does it suit you?", a: "Take a moment to reflect and share honestly." },
    { q: "If you had to describe me in one word, what would it be?", a: "Take a moment to reflect and share honestly." },
    { q: "What decade do you think we would have thrived in?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the weirdest dream you have ever had about us?", a: "Take a moment to reflect and share honestly." },
    { q: "What moment from your childhood shaped who you are today?", a: "Take a moment to reflect and share honestly." },
    { q: "Who taught you the most about love?", a: "Take a moment to reflect and share honestly." },
    { q: "What is a lesson your parents taught you without meaning to?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the biggest risk you have ever taken that is not about me?", a: "Take a moment to reflect and share honestly." },
    { q: "What small thing do you do every day that no one notices?", a: "Take a moment to reflect and share honestly." },
    { q: "What are you most proud of that you never talk about?", a: "Take a moment to reflect and share honestly." },
    { q: "What does your ideal weekend look like on paper?", a: "Take a moment to reflect and share honestly." },
    { q: "What is a compliment you never forgot?", a: "Take a moment to reflect and share honestly." },
    { q: "What was a defining moment in your teenage years?", a: "Take a moment to reflect and share honestly." },
    { q: "What hobby would you pick up if you had unlimited time?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the best decision you have ever made?", a: "Take a moment to reflect and share honestly." },
    { q: "Who in your life challenges you to grow?", a: "Take a moment to reflect and share honestly." },
    { q: "What memory of us makes you smile instantly?", a: "Take a moment to reflect and share honestly." },
    { q: "What is something about yourself you are still discovering?", a: "Take a moment to reflect and share honestly." },
    { q: "What does your favorite smell remind you of?", a: "Take a moment to reflect and share honestly." },
    { q: "What fear drives more of your decisions than you realize?", a: "Take a moment to reflect and share honestly." },
    { q: "When did you last feel truly alone, and what did you need?", a: "Take a moment to reflect and share honestly." },
    { q: "What part of yourself do you hide from most people?", a: "Take a moment to reflect and share honestly." },
    { q: "What has been your biggest emotional turning point in life?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you know when you can trust someone completely?", a: "Take a moment to reflect and share honestly." },
    { q: "What grief are you still carrying quietly?", a: "Take a moment to reflect and share honestly." },
    { q: "What lie do you tell yourself most often?", a: "Take a moment to reflect and share honestly." },
    { q: "When did you last forgive yourself for something?", a: "Take a moment to reflect and share honestly." },
    { q: "What do you need to hear when you are overwhelmed?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the hardest thing you have ever admitted to yourself?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you want to be loved when you are struggling?", a: "Take a moment to reflect and share honestly." },
    { q: "What story do you tell yourself about why you are not enough?", a: "Take a moment to reflect and share honestly." },
    { q: "What relationship in your past taught you the most about yourself?", a: "Take a moment to reflect and share honestly." },
    { q: "What does safety feel like in your body?", a: "Take a moment to reflect and share honestly." },
    { q: "What shame have you been carrying longer than you should?", a: "Take a moment to reflect and share honestly." },
    { q: "What word describes how you feel when we are truly close?", a: "Take a moment to reflect and share honestly." },
    { q: "What non-physical thing I do makes you feel the most connected?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your favorite way to end a day together?", a: "Take a moment to reflect and share honestly." },
    { q: "What part of our intimacy do you wish we talked about more?", a: "Take a moment to reflect and share honestly." },
    { q: "What sound or sigh from me do you love hearing?", a: "Take a moment to reflect and share honestly." },
    { q: "What temperature, texture, or fabric makes you feel most sensual?", a: "Take a moment to reflect and share honestly." },
    { q: "What moment between us felt the most electric?", a: "Take a moment to reflect and share honestly." },
    { q: "What do you find beautiful about me that I overlook?", a: "Take a moment to reflect and share honestly." },
    { q: "What kind of eye contact makes you feel closest?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your favorite way to be held?", a: "Take a moment to reflect and share honestly." },
    { q: "What small gesture from you makes me feel most desired?", a: "Take a moment to reflect and share honestly." },
    { q: "What fantasy would you be curious to explore with me?", a: "Take a moment to reflect and share honestly." },
    { q: "What does foreplay mean to you beyond the physical?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the most attractive thing about our dynamic together?", a: "Take a moment to reflect and share honestly." },
    { q: "What mood or energy makes you most open to intimacy?", a: "Take a moment to reflect and share honestly." },
    { q: "What does richness mean to you beyond money?", a: "Take a moment to reflect and share honestly." },
    { q: "Where do you picture us when we are old?", a: "Take a moment to reflect and share honestly." },
    { q: "What adventure do you refuse to die without taking?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you want us to divide responsibilities in our future home?", a: "Take a moment to reflect and share honestly." },
    { q: "What does a thriving partnership look like twenty years from now?", a: "Take a moment to reflect and share honestly." },
    { q: "What values do you want our home to stand for?", a: "Take a moment to reflect and share honestly." },
    { q: "What kind of community do you want us to build together?", a: "Take a moment to reflect and share honestly." },
    { q: "What skill do you want us to learn as a couple?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you want to handle big decisions that scare us?", a: "Take a moment to reflect and share honestly." },
    { q: "What role do you want travel to play in our life together?", a: "Take a moment to reflect and share honestly." },
    { q: "What are your non-negotiables for how we treat each other?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you picture our relationship evolving through major life changes?", a: "Take a moment to reflect and share honestly." },
    { q: "What does financial partnership mean to you?", a: "Take a moment to reflect and share honestly." },
    { q: "What project or cause would you love for us to tackle together?", a: "Take a moment to reflect and share honestly." },
    { q: "What legacy do you want us to leave in our relationship?", a: "Take a moment to reflect and share honestly." }
  ],
    takeaways: [ 'Focus: What you will get from this guide.', 'Not every moment calls for the same depth of conversation.', 'The environment shapes the conversation.' ],
  sections: [
    { h2: "What you will get from this guide", p: "", list: ["A proven 5-step framework for meaningful couple conversations", "150+ curated questions organized by depth and theme", "A comparison table to choose the right connection level for any moment", "Practical advice on how to listen, respond, and build intimacy over time", "Bonus tips for turning questions into a lasting weekly ritual"] },
    { h2: "The five connection levels at a glance", p: "Not every moment calls for the same depth of conversation. This table helps you match the right level to the right mood." },
    { h2: "Step 1: Prepare the space", p: "The environment shapes the conversation. You do not need candles and rose petals, but a few simple adjustments make a significant difference. Put phones in another room. Sit facing each other or side by side with no screen between you. Choose a time when neither of you is hungry, exhausted, or rushed. Even ten minutes of undivided attention beats an hour of distracted presence. Set one ground rule: no fixing, no solving. The goal is understanding, not problem-solving. If an answer makes you uncomfortable, stay curious instead of defensive. You are not interviewing each other; you are exploring together." },
    { h2: "Step 2: Choose the right depth", p: "The biggest mistake couples make is going too deep too fast. Depth without trust feels like an interrogation. Start at level 1 or 2 unless you already know you both have the bandwidth for more. Pay attention to body language: crossed arms, fidgeting, or avoiding eye contact are signals to lighten up. Leaning in, eye contact, and relaxed shoulders mean you can go deeper. If you are not sure where to start, try this: ask your partner to pick a number from 1 to 5 based on how they are feeling right now. Match that level and follow their lead." },
    { h2: "Step 3: Ask with intention", p: "How you ask matters as much as what you ask. Use an open, warm tone. Start with a softener: I have been curious about something or Can I ask you a question that popped into my head? This signals safety instead of interrogation. After your partner answers, pause before responding. A three-second silence often invites them to go deeper. Reflect back what you heard: It sounds like you felt or That makes me understand you better. Avoid judgment, advice, or turning the answer into a debate. Your only job is to receive what they share with gratitude. When both partners feel heard without being fixed, trust compounds quickly." },
    { h2: "Step 4: Reflect together", p: "The conversation does not end when the question is answered. Reflection is where the real connection happens. After each answer, take a moment to sit with what was shared. You can say: Thank you for telling me that, or I never saw it that way before. These small validations are powerful. They tell your partner their honesty is safe with you. If something they share stirs an emotion in you, name it gently. Hearing that makes me feel closer to you. Shared reflection turns a Q A session into a bonding experience that both of you will remember long after the conversation ends." },
    { h2: "Step 5: Repeat and build a ritual", p: "Consistency matters more than intensity. A ten-minute check-in every week will deepen your connection more than a single four-hour marathon once a year. A 2023 study in the Journal of Social and Personal Relationships found that couples who ask each other novel questions report higher intimacy levels. Pick a recurring slot — Sunday morning coffee, Friday evening wind-down, or a mid-week walk. Make it your thing. Over time, these conversations become a safe container where both of you know you can bring anything. Keep a running list of questions that sparked the best conversations. Revisit them months later and notice how your answers change. Growth becomes visible when you compare where you were to where you are now. The ritual itself becomes the anchor that keeps you connected through busy seasons and quiet ones alike." },
    { h2: "A final thought", p: "You do not need a perfect question. You need a quiet moment, a willing heart, and the courage to start. The questions above are tools, not rules. Adapt them, remix them, and let them evolve with your relationship. The goal is not to ask every question on this list. The goal is to build a habit of curiosity that keeps you discovering each other — for as long as you choose to be together." }
  ],
  related: [
    { slug: "50-deep-questions-for-couples", title: "50 Deep Questions for Couples to Reconnect | Captain Bond", description: "Strengthen your bond with 50 deep questions for couples organized by theme — vulnerability, past, values, love, and drea" },
    { slug: "best-couple-app-2026", title: "Best Couple App 2026: 5 Relationship Apps Tested & Compared | Captain Bond", description: "We tested 5 couple apps in 2026 — Captain Bond, Paired, LoveNudge, Gottman Card Decks, and Lasting. Compare features, pr" },
    { slug: "couple-communication-exercises", title: "10 Couple Communication Exercises to Deepen Your Connection | Captain Bond", description: "10 practical communication exercises for couples — from mirroring to conflict scripts — backed by relationship science. " }
  ],
  geoBlock: "Comprehensive question guides rank well in AI overviews because they cover the full intent spectrum — icebreakers through deep prompts. A complete, themed guide is what engines cite for 'questions for couples' queries across depths.",
  cta: { heading: 'Ready?', text: 'Discover Captain Bond.', href: "/couple" },
  endingQuestion: "Which question will you ask each other first?",
};
