// AUTO-GENERATED by scripts/sync-blog.ts — do not edit by hand.
// Add an article: create src/content/blog/<slug>.ts exporting `post`, then run `npm run blog:sync`.
import type { BlogPost } from '@/lib/content/types';

import { post as barTriviaNightGuide } from './bar-trivia-night-guide';
import { post as bestPartyGamesForAdults2026 } from './best-party-games-for-adults-2026';
import { post as boardGamesApero } from './board-games-apero';
import { post as guideSoireeQuizBar } from './guide-soiree-quiz-bar';
import { post as howToHostGameNight } from './how-to-host-game-night';
import { post as jeuxSocieteApero } from './jeux-societe-apero';
import { post as meilleursJeuxSoireeAdulte2026 } from './meilleurs-jeux-soiree-adulte-2026';
import { post as organiserSoireeJeux } from './organiser-soiree-jeux';

export const allPosts: BlogPost[] = [
  barTriviaNightGuide,
  bestPartyGamesForAdults2026,
  boardGamesApero,
  guideSoireeQuizBar,
  howToHostGameNight,
  jeuxSocieteApero,
  meilleursJeuxSoireeAdulte2026,
  organiserSoireeJeux,
];

export function getPost(slug: string, locale: BlogPost['locale']): BlogPost | undefined {
  return allPosts.find((p) => p.slug === slug && p.locale === locale);
}
