import type { BlogPost } from '@/lib/content/types';

// MIGRATED from legacy page.tsx — section bodies + FAQ answers + geoBlock to enrich.
export const post: BlogPost = {
  slug: "questions-couple-guide-complet",
  locale: "fr",
  hub: "couple" as const,
  title: "Questions pour un Couple : Le Guide Complet pour se Connecter Plus Profondément | Captain Bond",
  description: "150+ questions de couple à travers 5 niveaux de connexion — fun, découverte, profond, intime et futur. Un rituel étape par étape pour transformer chaque conversation en vraie intimité.",
  frSlug: "couple-questions-complete-guide",
  ogImage: "/og/blog-questions-couple-guide-fr.webp",
  published: "2025-06-15",
  modified: "2026-07-10",
  readTime: "X min de lecture",
  faq: [
    { q: "Quelle chanson nous décrit le mieux en tant que couple ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est le souvenir le plus drôle que tu as de nous deux ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si notre relation était un film, quel en serait le titre ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est ton plat préféré que je cuisine — ou que tu aimerais que je cuisine ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si tu pouvais avoir un super-pouvoir, lequel choisirais-tu ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle est la chose la plus embarrassante que tu aies faite pour me faire rire ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Plutôt soirée Netflix ou soirée jeux de société ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si on gagnait au loto demain, quelle est la première chose que tu achèterais ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est le pire film que tu aimes secrètement ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle est notre meilleure blague privée ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si on devait vivre dans une série, laquelle choisirais-tu ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est ton souvenir denfance le plus absurde ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel surnom ridicule ta famille te donnait-elle ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Si tu devais décrire notre relation en un mot, que dirais-tu ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est le voyage de rêve que tu voudrais faire avec moi ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel moment de ton enfance t'a le plus marqué ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qui a eu la plus grande influence sur la personne que tu es devenue ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle est la leçon la plus importante que tes parents tâont apprise sans le vouloir ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est le plus grand risque que tu aies pris dans ta vie ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle petite chose fais-tu chaque jour que personne ne remarque ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "De quoi es-tu le plus fier sans jamais en parler ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est le meilleur conseil que tu aies jamais reçu ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel compliment ne pourras-tu jamais oublier ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est ton plus beau souvenir de nous deux ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu apprends encore sur toi-même ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle est la meilleure décision que tu aies prise dans ta vie ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que ton moi adolescent penserait de toi aujourd'hui ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle tradition de ton enfance aimerais-tu perpétuer ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle qualité chez moi as-tu mis du temps à remarquer ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel est ton objectif qui n'a rien à voir avec le travail ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle peur influence tes décisions plus que tu ne le réalises ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quand t'es-tu senti vraiment seul pour la dernière fois ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle partie de toi caches-tu à la plupart des gens ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel a été ton plus grand tournant émotionnel dans la vie ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Comment sais-tu que tu peux faire entièrement confiance à quelqu'un ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel chagrin portes-tu encore en silence ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel mensonge te répètes-tu le plus souvent ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quand t'es-tu pardonné quelque chose pour la dernière fois ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "De quoi as-tu besoin quand tu es submergé ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle est la chose la plus difficile que tu te sois avouée ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Comment veux-tu être aimé quand tu traverses une tempête ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle histoire te racontes-tu sur pourquoi tu n'es pas assez ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce qui te fait te sentir en sécurité dans ton corps ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle honte portes-tu depuis trop longtemps ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "De quoi as-tu besoin pour pleurer vraiment ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel mot décrit ce que tu ressens quand on est vraiment proches ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que je fais, sans contact physique, qui te connecte le plus ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle est ta façon préférée de terminer une journée avec moi ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel son ou soupir de moi aimes-tu entendre ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle texture ou matière te rend le plus sensuel ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel moment entre nous a été le plus électrique ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que tu trouves beau chez moi que je néglige ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel regard te fait te sentir le plus proche ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Comment aimes-tu être enlacé ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel petit geste de toi me fait me sentir le plus désirée ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle fantaisie serais-tu curieux d'explorer avec moi ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Qu'est-ce que les préliminaires signifient pour toi au-delà du physique ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle est la chose la plus attirante dans notre dynamique ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle humeur ou énergie te rend le plus ouvert à l'intimité ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel baiser de nous reste gravé dans ta mémoire ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "À quoi ressemble la richesse pour toi au-delà de l'argent ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Où nous vois-tu quand nous serons vieux ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle aventure ne veux-tu pas vivre sans l'avoir tentée ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Comment veux-tu qu'on répartisse les responsabilités dans notre futur foyer ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "À quoi ressemble un partenariat épanoui dans vingt ans ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelles valeurs veux-tu que notre foyer incarne ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle communauté veux-tu qu'on construise ensemble ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quelle compétence veux-tu apprendre en tant que couple ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Comment veux-tu gérer les grandes décisions qui nous effraient ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel rôle veux-tu que les voyages jouent dans notre vie commune ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quels sont tes non-négociables sur la façon dont on se traite ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Comment vois-tu notre relation évoluer à travers les grands changements de la vie ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Que signifie le partenariat financier pour toi ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel projet ou cause aimerais-tu qu'on entreprenne ensemble ?", a: "Prenez un moment pour réfléchir et partager honnêtement." },
    { q: "Quel héritage veux-tu qu'on laisse dans notre relation ?", a: "Prenez un moment pour réfléchir et partager honnêtement." }
  ],
  takeaways: [
    'TODO takeaway 1', 'TODO takeaway 2', 'TODO takeaway 3'
  ],
  sections: [
    { h2: "Ce que vous allez découvrir dans ce guide", p: "", list: ["Un cadre en 5 étapes pour des conversations de couple qui comptent", "150+ questions organisées par profondeur et thème", "Un tableau comparatif pour choisir le bon niveau de connexion à chaque moment", "Des conseils pratiques pour écouter, répondre et construire l intimité dans la durée", "Des astuces pour transformer les questions en un rituel hebdomadaire durable"] },
    { h2: "Les cinq niveaux de connexion en un coup d œil", p: "Chaque moment ne réclame pas la même profondeur de conversation. Ce tableau vous aide à choisir le bon niveau pour la bonne humeur." },
    { h2: "Étape 1 : Préparer l espace", p: "L environnement façonne la conversation. Pas besoin de bougies et de pétales de rose, mais quelques ajustements simples font toute la différence. Mettez les téléphones dans une autre pièce. Asseyez-vous face à face ou côte à côte sans écran entre vous. Choisissez un moment où ni l un ni l autre n a faim, n est épuisé ou pressé. Même dix minutes d attention totale valent mieux qu une heure de présence distraite. Fixez une règle de base : pas de réparation, pas de solution. Le but est la compréhension, pas la résolution de problèmes. Si une réponse vous met mal à l aise, restez curieux plutôt que sur la défensive. Vous ne vous interviewez pas, vous explorez ensemble." },
    { h2: "Étape 2 : Choisir la bonne profondeur", p: "La plus grande erreur que font les couples est d aller trop profond trop vite. La profondeur sans confiance ressemble à un interrogatoire. Commencez au niveau 1 ou 2 sauf si vous savez que vous avez tous les deux l espace nécessaire pour plus. Observez le langage corporel : bras croisés, agitation, ou éviter le regard sont des signaux pour alléger. Se pencher, un regard soutenu et des épaules détendues signifient que vous pouvez aller plus loin. Si vous ne savez pas par où commencer, essayez ceci : demandez à votre partenaire de choisir un chiffre de 1 à 5 selon son état d esprit du moment. Alignez-vous sur ce niveau et suivez son rythme." },
    { h2: "Étape 3 : Poser la question avec intention", p: "La façon dont vous posez la question compte autant que la question elle-même. Utilisez un ton ouvert et chaleureux. Commencez par un adoucisseur : « Je me demandais quelque chose… » ou « Je peux te poser une question qui m est venue ? » Cela signale la sécurité plutôt que l interrogatoire. Après la réponse de votre partenaire, faites une pause avant de répondre. Un silence de trois secondes les invite souvent à aller plus loin. Reformulez ce que vous avez entendu : « On dirait que tu as ressenti… » ou « Ça me permet de mieux te comprendre. » Évitez le jugement, les conseils, ou de transformer la réponse en débat. Votre seul rôle est de recevoir ce qu ils partagent avec gratitude. Quand les deux partenaires se sentent entendus sans être réparés, la confiance s accumule rapidement." },
    { h2: "Étape 4 : Réfléchir ensemble", p: "La conversation ne s arrête pas quand la question est répondue. La réflexion est là où la vraie connexion opère. Après chaque réponse, prenez un moment pour accueillir ce qui a été partagé. Vous pouvez dire : « Merci de m avoir dit ça » ou « Je n avais jamais vu les choses comme ça. » Ces petites validations sont puissantes. Elles disent à votre partenaire que son honnêteté est en sécurité avec vous. Si ce qu ils partagent éveille une émotion en vous, nommez-la doucement. « Entendre ça me rend plus proche de toi. » La réflexion partagée transforme une session de questions-réponses en une expérience de rapprochement que vous garderez tous les deux longtemps après la fin de la conversation." },
    { h2: "Étape 5 : Répéter et créer un rituel", p: "La régularité compte plus que l intensité. Un check-in de dix minutes chaque semaine approfondira votre connexion plus qu un marathon de quatre heures une fois par an. Une étude de 2023 dans le Journal of Social and Personal Relationships a montré que les couples qui se posent des questions originales rapportent des niveaux d intimité plus élevés. Choisissez un créneau récurrent — café du dimanche matin, débrief du vendredi soir, ou une promenade en milieu de semaine. Faites-en votre truc. Avec le temps, ces conversations deviennent un espace sûr où chacun peut amener n importe quoi. Gardez une liste des questions qui ont déclenché les meilleures conversations. Revisitez-les quelques mois plus tard et remarquez comment vos réponses ont changé. La croissance devient visible quand vous comparez où vous étiez à où vous êtes maintenant. Le rituel lui-même devient l ancre qui vous maintient connectés à travers les saisons chargées comme les plus calmes." },
    { h2: "Un dernier mot", p: "Vous n avez pas besoin de la question parfaite. Vous avez besoin d un moment calme, d un cœur ouvert et du courage de commencer. Les questions ci-dessus sont des outils, pas des règles. Adaptez-les, mélangez-les et laissez-les évoluer avec votre relation. Le but n est pas de poser chaque question de cette liste. Le but est de construire une habitude de curiosité qui vous fait continuer à vous découvrir — aussi longtemps que vous choisissez d être ensemble." }
  ],
  related: [
    { slug: "50-questions-profondes-couple", title: "50 questions profondes pour couple : se reconnecter | Captain Bond", description: "Retrouvez une complicité durable avec 50 questions profondes pour couple en français. Vulnérabilité, passé, valeurs, amo" },
    { slug: "etude-donnees-connexion-couple", title: "Étude données connexion couple : 1 200+ sessions analysées | Captain Bond", description: "Analyse de 1 237 sessions Captain Bond : scores d'harmonie, préférences de questions, moments clés pour la connexion. Do" },
    { slug: "exercices-communication-couple", title: "10 exercices de communication pour couple : renforcez votre lien | Captain Bond", description: "10 exercices de communication pratiques pour les couples — du mirroring aux scripts de conflit — validés par la science " }
  ],
  geoBlock: "Les guides complets de questions performent dans les aperçus IA car ils couvrent tout le spectre, du brise-glace aux sujets profonds. Un guide thématique complet est ce que les moteurs citent pour 'questions en couple'.",
  cta: { heading: 'Ready?', text: 'Discover Captain Bond.', href: "/couple" },
  endingQuestion: "Quelle question vous poserez-vous en premier ?",
};
