import type { BlogPost } from '@/lib/content/types';

// MIGRATED from legacy page.tsx — section bodies + FAQ answers + geoBlock to enrich.
export const post: BlogPost = {
  slug: "questions-pour-couple",
  locale: "fr",
  hub: "couple" as const,
  title: "150 Questions for Couples: From Fun to Deep | Captain Bond",
  description: "A curated list of couple questions covering fun, intimacy, values and future dreams — plus a simple ritual to turn them into real connection.",
  frSlug: "questions-pour-couple",
  ogImage: "/og/blog-questions-couple-en.webp",
  published: "2025-06-01",
  modified: "2026-07-10",
  readTime: "X min de lecture",
  faq: [
    { q: "What song immediately makes you dance, no matter where you are?", a: "Take a moment to reflect and share honestly." },
    { q: "Which fictional character would you want as a roommate?", a: "Take a moment to reflect and share honestly." },
    { q: "Pineapple on pizza: yes, no, or only if no one is watching?", a: "Take a moment to reflect and share honestly." },
    { q: "If you could have any superpower for one day, what would it be?", a: "Take a moment to reflect and share honestly." },
    { q: "What was your most ridiculous childhood fear?", a: "Take a moment to reflect and share honestly." },
    { q: "Which meal could you eat every day for a month without getting bored?", a: "Take a moment to reflect and share honestly." },
    { q: "If we could teleport this weekend, where would we go?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the worst movie you secretly love?", a: "Take a moment to reflect and share honestly." },
    { q: "Cats or dogs — and has your answer changed over time?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your guiltiest-pleasure TV show?", a: "Take a moment to reflect and share honestly." },
    { q: "If you were a cocktail, what would you be called?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the funniest thing that happened to you this week?", a: "Take a moment to reflect and share honestly." },
    { q: "Would you rather speak every language or play every instrument?", a: "Take a moment to reflect and share honestly." },
    { q: "What random skill do you wish you had?", a: "Take a moment to reflect and share honestly." },
    { q: "Which celebrity would you want to have dinner with?", a: "Take a moment to reflect and share honestly." },
    { q: "What did you want to be when you were ten years old?", a: "Take a moment to reflect and share honestly." },
    { q: "Who was your first real role model?", a: "Take a moment to reflect and share honestly." },
    { q: "What family tradition do you want to keep alive?", a: "Take a moment to reflect and share honestly." },
    { q: "What memory always makes you smile, no matter how many times you recall it?", a: "Take a moment to reflect and share honestly." },
    { q: "How did your parents show love when you were growing up?", a: "Take a moment to reflect and share honestly." },
    { q: "What is the best advice you have ever received?", a: "Take a moment to reflect and share honestly." },
    { q: "What book changed your perspective on life?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your proudest non-work achievement?", a: "Take a moment to reflect and share honestly." },
    { q: "What does a perfect Sunday look like for you?", a: "Take a moment to reflect and share honestly." },
    { q: "What is something people often misunderstand about you?", a: "Take a moment to reflect and share honestly." },
    { q: "What value would you never compromise, even under pressure?", a: "Take a moment to reflect and share honestly." },
    { q: "When do you feel most like yourself?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your earliest vivid memory?", a: "Take a moment to reflect and share honestly." },
    { q: "What friendship taught you the most about trust?", a: "Take a moment to reflect and share honestly." },
    { q: "What place feels most like home to you?", a: "Take a moment to reflect and share honestly." },
    { q: "What fear have you never said out loud?", a: "Take a moment to reflect and share honestly." },
    { q: "When did you first feel truly understood by another person?", a: "Take a moment to reflect and share honestly." },
    { q: "What part of your past has shaped you the most?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you process grief when it shows up?", a: "Take a moment to reflect and share honestly." },
    { q: "What does vulnerability mean to you in practice?", a: "Take a moment to reflect and share honestly." },
    { q: "What is a wound you are still quietly healing?", a: "Take a moment to reflect and share honestly." },
    { q: "When do you feel lonely even with other people around?", a: "Take a moment to reflect and share honestly." },
    { q: "What do you need when you are sad but rarely ask for?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your biggest insecurity, and where does it come from?", a: "Take a moment to reflect and share honestly." },
    { q: "How has your definition of love changed over the years?", a: "Take a moment to reflect and share honestly." },
    { q: "What are you most afraid to fail at?", a: "Take a moment to reflect and share honestly." },
    { q: "What moment in life made you grow up quickly?", a: "Take a moment to reflect and share honestly." },
    { q: "What do you wish your younger self had known?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you express anger, and how do you wish you expressed it?", a: "Take a moment to reflect and share honestly." },
    { q: "What does forgiveness look like for you?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your favorite way to be touched non-sexually?", a: "Take a moment to reflect and share honestly." },
    { q: "What smell or sound instantly relaxes you?", a: "Take a moment to reflect and share honestly." },
    { q: "What is something I do that makes you feel genuinely desired?", a: "Take a moment to reflect and share honestly." },
    { q: "What time of day do you feel most connected to your body?", a: "Take a moment to reflect and share honestly." },
    { q: "What fantasy would you feel safe sharing with me?", a: "Take a moment to reflect and share honestly." },
    { q: "What does seduction mean to you beyond the physical?", a: "Take a moment to reflect and share honestly." },
    { q: "What outfit makes you feel most confident?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your favorite memory of us being close?", a: "Take a moment to reflect and share honestly." },
    { q: "What kind of compliment genuinely turns you on?", a: "Take a moment to reflect and share honestly." },
    { q: "What is one thing you would like to try together?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you most like to be kissed?", a: "Take a moment to reflect and share honestly." },
    { q: "What is your favorite part of my body, and why?", a: "Take a moment to reflect and share honestly." },
    { q: "What mood or setting helps you feel most romantic?", a: "Take a moment to reflect and share honestly." },
    { q: "What is a turn-on for you that has nothing to do with touch?", a: "Take a moment to reflect and share honestly." },
    { q: "What song puts you in the mood?", a: "Take a moment to reflect and share honestly." },
    { q: "What does your ideal life look like in five years?", a: "Take a moment to reflect and share honestly." },
    { q: "Where would you like to live if money were no object?", a: "Take a moment to reflect and share honestly." },
    { q: "What kind of parent would you want to be, if at all?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you feel about money and freedom?", a: "Take a moment to reflect and share honestly." },
    { q: "What role does faith or spirituality play in your life?", a: "Take a moment to reflect and share honestly." },
    { q: "What cause would you dedicate your life to?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you want us to handle conflict as a team?", a: "Take a moment to reflect and share honestly." },
    { q: "What does a healthy partnership look like to you?", a: "Take a moment to reflect and share honestly." },
    { q: "What adventures are on your bucket list?", a: "Take a moment to reflect and share honestly." },
    { q: "How important is community to you?", a: "Take a moment to reflect and share honestly." },
    { q: "What legacy do you want to leave behind?", a: "Take a moment to reflect and share honestly." },
    { q: "What does retirement look like in your dreams?", a: "Take a moment to reflect and share honestly." },
    { q: "How do you want to celebrate milestones together?", a: "Take a moment to reflect and share honestly." },
    { q: "What are your non-negotiables in a relationship?", a: "Take a moment to reflect and share honestly." },
    { q: "What skills do you want to learn together?", a: "Take a moment to reflect and share honestly." }
  ],
  takeaways: [
    'TODO takeaway 1', 'TODO takeaway 2', 'TODO takeaway 3'
  ],
  sections: [
    { h2: "Why questions matter for couples", p: "Most couples do not run out of love; they run out of novelty. Daily logistics — groceries, bills, schedules — crowd out the deeper conversations that once came naturally. Questions are the simplest technology for reversing that drift. They create a pocket of attention where your partner becomes interesting again, not because they changed, but because you decided to look closer. A good question does not demand a perfect answer. It invites honesty. It gives permission to say the thing that normally stays quiet. Over time, these small disclosures become the fabric of intimacy: the feeling that someone knows you, not just the version you perform for the world. Love is not about finding the right person, but creating a right relationship through the questions you dare to ask. This is what makes questions the cheapest, most powerful tool in any relationship. They require no app, no subscription, no special setting — just two people and the willingness to be curious about each other again." },
    { h2: "How to use this list", p: "Quantity is not the goal. Connection is. Here is a simple ritual that makes the most of these prompts: The prompts below are grouped by theme and intensity. You do not need to answer all 150 in one night. Dip in, skip around, and come back when the moment feels right. If you want hundreds more prompts generated for you, the Captain Bond couple mode builds fresh question decks every session.", list: ["Pick a weekly slot. Twenty minutes is enough. Put phones in another room.", "One person asks, the other answers. Then swap roles. The listener stays curious instead of problem-solving.", "Create a safety zone. Either of you can pass on any question without explaining why.", "Follow the energy. If an answer opens a door, walk through it instead of rushing to the next prompt."] },
    { h2: "Fun and light questions", p: "Use these when you want to laugh, remember that you enjoy each other, or break a tense mood. Playfulness is underrated glue in long-term relationships." },
    { h2: "Getting-to-know-you questions", p: "Even partners who have been together for years can discover new rooms in each other. These prompts explore history, values and the small details that make a person feel unique." },
    { h2: "Deep and emotional questions", p: "Go here when the house is quiet, you both have bandwidth, and you want to feel genuinely close. These questions ask for vulnerability, so take them slowly and without pressure." },
    { h2: "Intimate and spicy questions", p: "Desire starts in the mind. These prompts stay classy while inviting you to talk about attraction, touch and what makes you feel wanted. Use them to build anticipation and clarity at the same time." },
    { h2: "Future and values questions", p: "Shared direction is what turns chemistry into partnership. These questions help you calibrate where you are heading and what you each need along the way." },
    { h2: "A final thought", p: "You do not need the perfect question. You need the courage to ask and the patience to listen. The list above is a starting point. The real magic happens in the follow-up, the pause, the laugh, the awkward silence you sit through together. Keep a few favorites in your back pocket and pull them out when life starts to feel transactional. Your relationship will thank you." }
  ],
  related: [
    { slug: "50-questions-profondes-couple", title: "50 questions profondes pour couple : se reconnecter | Captain Bond", description: "Retrouvez une complicité durable avec 50 questions profondes pour couple en français. Vulnérabilité, passé, valeurs, amour et rêves — pour des soirées qui rapprochent." },
    { slug: "meilleure-application-couple-2026", title: "Meilleure application couple 2026 : 5 applis testées & comparées | Captain Bond", description: "Nous avons testé 5 applications couple en 2026 — Captain Bond, Paired, LoveNudge, Gottman Card Decks et Lasting. Comparez les fonctionnalités, les prix et trouvez la meilleure appli pour votre relation." },
    { slug: "exercices-communication-couple", title: "10 exercices de communication pour couple : renforcez votre lien | Captain Bond", description: "10 exercices de communication pratiques pour les couples — du mirroring aux scripts de conflit — validés par la science des relations. Renforcez votre connexion dès aujourd'hui." }
  ],
  geoBlock: "Les couples demandent de plus en plus de prompts de conversation à l'IA. Un ensemble structuré par thème offre aux moteurs une source claire et citable pour 'questions en couple', toutes langues confondues.",
  cta: { heading: 'Ready?', text: 'Discover Captain Bond.', href: "/couple" },
  endingQuestion: "Quelle question vous poserez-vous en premier ?",
};
