// AUTO-GENERATED by scripts/sync-legacy.ts — do not edit manually.
// Bodies of legacy articles live in their original page.tsx; this mirrors
// only their SEO metadata so sitemap + audit cover every article.
import type { BlogPostLite } from '../lib/content/types';

export const legacyPosts: BlogPostLite[] = [
  {
    "slug": "50-deep-questions-for-couples",
    "locale": "en",
    "title": "50 Deep Questions for Couples to Reconnect | Captain Bond",
    "description": "Strengthen your bond with 50 deep questions for couples organized by theme — vulnerability, past, values, love, and dreams. Reconnect meaningfully starting tonight.",
    "frSlug": "50-questions-profondes-couple",
    "ogImage": "/og/blog-deep-questions-en.webp",
    "published": "2025-07-01",
    "modified": "2025-07-03"
  },
  {
    "slug": "best-couple-app-2026",
    "locale": "en",
    "title": "Best Couple App 2026: 5 Relationship Apps Tested & Compared | Captain Bond",
    "description": "We tested 5 couple apps in 2026 — Captain Bond, Paired, LoveNudge, Gottman Card Decks, and Lasting. Compare features, pricing, and find the best app for your relationship.",
    "frSlug": "meilleure-application-couple-2026",
    "ogImage": "/og/blog-best-couple-app-en.webp",
    "published": "2025-06-20",
    "modified": "2026-07-10"
  },
  {
    "slug": "best-party-games-for-large-groups",
    "locale": "en",
    "title": "Best Party Games for Large Groups in 2026: 10+ People Games | Captain Bond",
    "description": "The ultimate guide to party games for large groups of 10-50+ people. No app needed, phone-controlled, TV-displayed party games that everyone can play.",
    "frSlug": "meilleurs-jeux-de-soiree-grand-groupe",
    "ogImage": "/og/blog-party-large-groups-en.webp",
    "published": "2025-07-04",
    "modified": "2026-07-10"
  },
  {
    "slug": "couple-communication-exercises",
    "locale": "en",
    "title": "10 Couple Communication Exercises to Deepen Your Connection | Captain Bond",
    "description": "10 practical communication exercises for couples — from mirroring to conflict scripts — backed by relationship science. Strengthen your bond starting today.",
    "frSlug": "exercices-communication-couple",
    "ogImage": "/og/blog-communication-en.webp",
    "published": "2025-06-10",
    "modified": "2026-07-10"
  },
  {
    "slug": "couple-connection-data-study",
    "locale": "en",
    "title": "Couple Connection Data Study: Insights from 1,200+ Real Sessions | Captain Bond",
    "description": "Original research from 1,237 Captain Bond couple sessions. Discover data on harmony scores, conversation depth preferences, and the science of connection.",
    "frSlug": "etude-donnees-connexion-couple",
    "ogImage": "/og/blog-data-study-en.webp",
    "published": "2025-07-01",
    "modified": "2025-07-03"
  },
  {
    "slug": "couple-questions-complete-guide",
    "locale": "en",
    "title": "Couple Questions for Deeper Connection: The Complete Guide | Captain Bond",
    "description": "150+ couple questions across 5 connection levels — fun, getting-to-know, deep, intimate, and future. A step-by-step ritual to turn every conversation into real intimacy.",
    "frSlug": "questions-couple-guide-complet",
    "ogImage": "/og/blog-couple-questions-guide-en.webp",
    "published": "2025-06-15",
    "modified": "2026-07-10"
  },
  {
    "slug": "halloween-party-games-adults",
    "locale": "en",
    "title": "Halloween Party Games for Adults: 10+ Spooky Games for 2026 | Captain Bond",
    "description": "The best Halloween party games for adults. Spooky icebreakers, costume contests, and group games for your 2026 Halloween party. No app needed.",
    "frSlug": "jeux-halloween-adultes",
    "ogImage": "/og/blog-halloween-en.webp",
    "published": "2025-07-04",
    "modified": "2025-07-04"
  },
  {
    "slug": "icebreaker-games-for-adults",
    "locale": "en",
    "title": "50 Icebreaker Games for Adults: Fun, No-Equipment Ideas for Any Group | Captain Bond",
    "description": "50 no-equipment icebreaker games for adults broken into 5 categories. Quick, team, virtual, get-to-know-you, and deep games for parties, work, and dates.",
    "frSlug": "jeux-brise-glace-adultes",
    "ogImage": "/og/party-en.webp",
    "published": "2025-06-15",
    "modified": "2026-07-10"
  },
  {
    "slug": "increase-bar-revenue-weeknight",
    "locale": "en",
    "title": "How to Increase Bar Revenue on Weeknights (No Extra Staff) | Captain Bond",
    "description": "5 proven strategies to boost Tuesday—Thursday bar revenue without hiring: themed nights, AI-powered entertainment, loyalty mechanics and more.",
    "frSlug": "augmenter-chiffre-bar-semaine",
    "ogImage": "/og/blog-bar-revenue-en.webp",
    "published": "2025-07-04",
    "modified": "2026-07-10"
  },
  {
    "slug": "questions-pour-couple",
    "locale": "en",
    "title": "150 Questions for Couples: From Fun to Deep | Captain Bond",
    "description": "A curated list of couple questions covering fun, intimacy, values and future dreams — plus a simple ritual to turn them into real connection.",
    "frSlug": "questions-pour-couple",
    "ogImage": "/og/blog-questions-couple-en.webp",
    "published": "2025-06-01",
    "modified": "2026-07-10"
  },
  {
    "slug": "questions-to-ask-your-partner",
    "locale": "en",
    "title": "Questions to Ask Your Partner: 100+ Deep, Fun & Intimate | Captain Bond",
    "description": "The ultimate list of 100+ questions to ask your partner — organized by relationship stage. Deep, fun and intimate questions for every couple.",
    "frSlug": "questions-a-poser-a-son-partenaire",
    "ogImage": "/og/blog-questions-partner-en.webp",
    "published": "2025-07-01",
    "modified": "2025-07-03"
  },
  {
    "slug": "questions-to-build-intimacy",
    "locale": "en",
    "title": "30 Questions to Build Intimacy: Deepen Your Connection Tonight | Captain Bond",
    "description": "30 intimacy-building questions for couples across emotional, physical, and intellectual dimensions. Strengthen your bond with conversations that matter.",
    "frSlug": "questions-pour-construire-intimite",
    "ogImage": "/og/blog-build-intimacy-en.webp",
    "published": "2025-06-12",
    "modified": "2026-07-10"
  },
  {
    "slug": "weekly-couple-ritual",
    "locale": "en",
    "title": "How to Create a Weekly Couple Ritual (20-Min Guide) | Captain Bond",
    "description": "A simple 20-minute weekly ritual that keeps your relationship connected, intentional, and intimate. Step-by-step guide with science-backed benefits.",
    "frSlug": "rituel-couple-hebdomadaire",
    "ogImage": "/og/blog-weekly-ritual-en.webp",
    "published": "2025-07-01",
    "modified": "2026-07-10"
  },
  {
    "slug": "50-questions-profondes-couple",
    "locale": "fr",
    "title": "50 questions profondes pour couple : se reconnecter | Captain Bond",
    "description": "Retrouvez une complicité durable avec 50 questions profondes pour couple en français. Vulnérabilité, passé, valeurs, amour et rêves — pour des soirées qui rapprochent.",
    "frSlug": "50-deep-questions-for-couples",
    "ogImage": "/og/blog-deep-questions-fr.webp",
    "published": "2025-07-01",
    "modified": "2025-07-03"
  },
  {
    "slug": "augmenter-chiffre-bar-semaine",
    "locale": "fr",
    "title": "Augmenter le Chiffre d'Affaires de son Bar en Semaine (Sans Embauche) | Captain Bond",
    "description": "5 stratégies testées pour booster les soirs de semaine dans votre bar : soirées à thème, divertissement IA, mécaniques de fidélité, et tournois. Aucun recrutement nécessaire.",
    "frSlug": "increase-bar-revenue-weeknight",
    "ogImage": "/og/blog-bar-revenue-fr.webp",
    "published": "2025-07-04",
    "modified": "2026-07-10"
  },
  {
    "slug": "etude-donnees-connexion-couple",
    "locale": "fr",
    "title": "Étude données connexion couple : 1 200+ sessions analysées | Captain Bond",
    "description": "Analyse de 1 237 sessions Captain Bond : scores d'harmonie, préférences de questions, moments clés pour la connexion. Données originales sur la communication de couple.",
    "frSlug": "couple-connection-data-study",
    "ogImage": "/og/blog-data-study-fr.webp",
    "published": "2025-07-01",
    "modified": "2025-07-03"
  },
  {
    "slug": "exercices-communication-couple",
    "locale": "fr",
    "title": "10 exercices de communication pour couple : renforcez votre lien | Captain Bond",
    "description": "10 exercices de communication pratiques pour les couples — du mirroring aux scripts de conflit — validés par la science des relations. Renforcez votre connexion dès aujourd'hui.",
    "frSlug": "couple-communication-exercises",
    "ogImage": "/og/blog-communication-fr.webp",
    "published": "2025-06-10",
    "modified": "2026-07-10"
  },
  {
    "slug": "jeux-brise-glace-adultes",
    "locale": "fr",
    "title": "50 jeux brise-glace pour adultes : idées fun sans matériel | Captain Bond",
    "description": "50 jeux brise-glace pour adultes classés en 5 catégories. Jeux rapides, pour faire connaissance, en équipe, virtuels et profonds. Zéro matériel nécessaire.",
    "frSlug": "icebreaker-games-for-adults",
    "ogImage": "/og/soiree-fr.webp",
    "published": "2025-06-15",
    "modified": "2025-07-03"
  },
  {
    "slug": "jeux-halloween-adultes",
    "locale": "fr",
    "title": "Jeux d'Halloween pour Adultes : 10+ Jeux pour une Soirée d'Enfer | Captain Bond",
    "description": "Les meilleurs jeux d'Halloween pour adultes : icebreakers effrayants, concours de costumes et jeux en groupe. Pas d'appli, que du fun.",
    "frSlug": "halloween-party-games-adults",
    "ogImage": "/og/blog-halloween-fr.webp",
    "published": "2025-07-04",
    "modified": "2026-07-10"
  },
  {
    "slug": "meilleure-application-couple-2026",
    "locale": "fr",
    "title": "Meilleure application couple 2026 : 5 applis testées & comparées | Captain Bond",
    "description": "Nous avons testé 5 applications couple en 2026 — Captain Bond, Paired, LoveNudge, Gottman Card Decks et Lasting. Comparez les fonctionnalités, les prix et trouvez la meilleure appli pour votre relation.",
    "frSlug": "best-couple-app-2026",
    "ogImage": "/og/blog-best-couple-app-fr.webp",
    "published": "2025-06-20",
    "modified": "2025-07-03"
  },
  {
    "slug": "meilleurs-jeux-de-soiree-grand-groupe",
    "locale": "fr",
    "title": "Meilleurs Jeux de Soirée pour Grands Groupes 2026 : 10-50+ Personnes | Captain Bond",
    "description": "Le guide ultime des jeux de soirée pour grands groupes de 10 à 50+ personnes. Pas d'appli nécessaire, jeux contrôlés par téléphone, affichés sur la TV.",
    "frSlug": "best-party-games-for-large-groups",
    "ogImage": "/og/blog-party-large-groups-fr.webp",
    "published": "2025-07-04",
    "modified": "2026-07-10"
  },
  {
    "slug": "questions-a-poser-a-son-partenaire",
    "locale": "fr",
    "title": "100+ questions à poser à son partenaire | Captain Bond",
    "description": "La liste ultime des 100+ questions profondes, fun et intimes à poser à son partenaire — classées par stade de relation. Du premier rendez-vous à la vie à deux.",
    "frSlug": "questions-to-ask-your-partner",
    "ogImage": "/og/blog-questions-partner-fr.webp",
    "published": "2025-07-01",
    "modified": "2025-07-03"
  },
  {
    "slug": "questions-couple-guide-complet",
    "locale": "fr",
    "title": "Questions pour un Couple : Le Guide Complet pour se Connecter Plus Profondément | Captain Bond",
    "description": "150+ questions de couple à travers 5 niveaux de connexion — fun, découverte, profond, intime et futur. Un rituel étape par étape pour transformer chaque conversation en vraie intimité.",
    "frSlug": "couple-questions-complete-guide",
    "ogImage": "/og/blog-questions-couple-guide-fr.webp",
    "published": "2025-06-15",
    "modified": "2026-07-10"
  },
  {
    "slug": "questions-pour-construire-intimite",
    "locale": "fr",
    "title": "30 questions pour construire l'intimité : rapprochez-vous dès ce soir | Captain Bond",
    "description": "30 questions pour construire l'intimité émotionnelle, physique et intellectuelle dans votre couple. Renforcez votre connexion avec des conversations qui comptent.",
    "frSlug": "questions-to-build-intimacy",
    "ogImage": "/og/blog-build-intimacy-fr.webp",
    "published": "2025-06-12",
    "modified": "2026-07-10"
  },
  {
    "slug": "questions-pour-couple",
    "locale": "fr",
    "title": "150 questions pour couple : du fun au profond | Captain Bond",
    "description": "Une liste de questions pour couple pour rire, se découvrir, aborder l'intimité et construire un futur commun — avec un rituel simple pour les intégrer au quotidien.",
    "frSlug": "questions-pour-couple",
    "ogImage": "/og/blog-questions-couple-fr.webp",
    "published": "2025-06-01",
    "modified": "2025-07-03"
  },
  {
    "slug": "rituel-couple-hebdomadaire",
    "locale": "fr",
    "title": "Comment créer un rituel de couple hebdomadaire (guide 20 min) | Captain Bond",
    "description": "Un rituel de couple simple de 20 minutes par semaine pour rester connectés, intentionnels et complices. Guide pas à pas avec bénéfices scientifiquement prouvés.",
    "frSlug": "weekly-couple-ritual",
    "ogImage": "/og/blog-weekly-ritual-fr.webp",
    "published": "2025-07-01",
    "modified": "2025-07-03"
  }
];
