// AUTO-GENERATED by scripts/sync-legacy.ts — do not edit manually.
// Bodies of legacy articles live in their original page.tsx; this mirrors
// only their SEO metadata so sitemap + audit cover every article.
import type { BlogPostLite } from '../lib/content/types';

export const legacyPosts: BlogPostLite[] = [];
