// Agent-facing SEO/GEO status report for the whole blog.
// Prints a per-post completeness table and writes .agents/blog-report.md.
// Run: `npm run blog:report`
import fs from 'fs';
import path from 'path';
import { allPosts } from '../src/content/blog';
import { legacyPosts } from '../src/content/legacy';

type Row = {
  kind: 'content' | 'legacy';
  locale: string;
  slug: string;
  hub: string;
  faq: number;
  sections: number;
  takeaways: number;
  geo: string;
  og: string;
  frSlug: string;
  related: number;
  score: number;
};

const rows: Row[] = [];

for (const p of allPosts) {
  const og = p.ogImage ? fs.existsSync(path.resolve('public', p.ogImage.replace(/^\//, ''))) : false;
  const checks = [
    (p.title?.length ?? 0) >= 10,
    (p.description?.length ?? 0) >= 50,
    og,
    (p.faq?.length ?? 0) >= 3,
    (p.sections?.length ?? 0) >= 3,
    (p.takeaways?.length ?? 0) >= 3,
    !!p.geoBlock && p.geoBlock.length >= 40,
    !!p.frSlug,
    (p.related?.length ?? 0) > 0,
  ];
  const score = Math.round((checks.filter(Boolean).length / checks.length) * 100);
  rows.push({
    kind: 'content',
    locale: p.locale,
    slug: p.slug,
    hub: p.hub ?? '-',
    faq: p.faq?.length ?? 0,
    sections: p.sections?.length ?? 0,
    takeaways: p.takeaways?.length ?? 0,
    geo: p.geoBlock && p.geoBlock.length >= 40 ? 'Y' : 'N',
    og: og ? 'Y' : 'N',
    frSlug: p.frSlug ? 'Y' : 'N',
    related: p.related?.length ?? 0,
    score,
  });
}

for (const p of legacyPosts) {
  const og = p.ogImage ? fs.existsSync(path.resolve('public', p.ogImage.replace(/^\//, ''))) : false;
  const checks = [
    (p.title?.length ?? 0) >= 10,
    (p.description?.length ?? 0) >= 50,
    og,
    !!p.frSlug,
  ];
  const score = Math.round((checks.filter(Boolean).length / checks.length) * 100);
  rows.push({
    kind: 'legacy',
    locale: p.locale,
    slug: p.slug,
    hub: '-',
    faq: -1,
    sections: -1,
    takeaways: -1,
    geo: 'n/a',
    og: og ? 'Y' : 'N',
    frSlug: p.frSlug ? 'Y' : 'N',
    related: -1,
    score,
  });
}

rows.sort((a, b) => a.kind.localeCompare(b.kind) || a.locale.localeCompare(b.locale) || a.slug.localeCompare(b.slug));

const avg = (arr: number[]) => (arr.length ? Math.round(arr.reduce((s, n) => s + n, 0) / arr.length) : 0);
const contentScores = rows.filter((r) => r.kind === 'content').map((r) => r.score);
const legacyScores = rows.filter((r) => r.kind === 'legacy').map((r) => r.score);

console.log('\n=== BLOG SEO/GEO REPORT ===');
console.log('kind  loc  hub      faq sec tak geo og  fr  rel  score  slug');
for (const r of rows) {
  console.log(
    `${r.kind.padEnd(7)} ${r.locale.padEnd(3)} ${r.hub.padEnd(8)} ` +
      `${String(r.faq).padEnd(3)} ${String(r.sections).padEnd(3)} ${String(r.takeaways).padEnd(3)} ` +
      `${r.geo.padEnd(3)} ${r.og.padEnd(3)} ${r.frSlug.padEnd(3)} ${String(r.related).padEnd(3)} ` +
      `${String(r.score).padEnd(5)}  ${r.slug}`,
  );
}
console.log(
  `\nContent avg score: ${avg(contentScores)}% (${contentScores.length} posts) | Legacy avg: ${avg(legacyScores)}% (${legacyScores.length} posts)`,
);
console.log('Flags: geo=GEO block, og=OG image file, fr=frSlug, rel=related links. -1/n/a = not applicable (legacy).');

const md = `# Blog SEO/GEO Report\n\nGenerated by \`npm run blog:report\`.\n\n` +
  `Content avg: **${avg(contentScores)}%** (${contentScores.length}) · Legacy avg: **${avg(legacyScores)}%** (${legacyScores.length})\n\n` +
  `| kind | loc | hub | faq | sec | tak | geo | og | fr | rel | score | slug |\n|---|---|---|---|---|---|---|---|---|---|---|---|\n` +
  rows
    .map(
      (r) =>
        `| ${r.kind} | ${r.locale} | ${r.hub} | ${r.faq} | ${r.sections} | ${r.takeaways} | ${r.geo} | ${r.og} | ${r.frSlug} | ${r.related} | ${r.score}% | ${r.slug} |`,
    )
    .join('\n') +
  '\n';
fs.writeFileSync(path.resolve('.agents/blog-report.md'), md);
console.log('Report written to .agents/blog-report.md\n');
