// Extract SEO metadata from the legacy `page.tsx` blog articles and emit a
// typed `legacyPosts` list so sitemap + audit cover ALL articles (legacy +
// content-layer) from one combined source — without touching the rich JSX
// bodies of the legacy articles.
//
// Run: `npm run blog:sync-legacy`
import fs from 'fs';
import path from 'path';
import type { BlogPostLite, BlogLocale } from '../src/lib/content/types';

const SITE = process.env.NEXT_PUBLIC_SITE_URL || 'https://captainbond.com';

const ROOTS: { dir: string; locale: BlogLocale }[] = [
  { dir: 'src/app/(marketing)/blog', locale: 'en' },
  { dir: 'src/app/fr/blog', locale: 'fr' },
];

/** Pull the `export const metadata = { ... }` object literal and eval it. */
function getMetadata(file: string): Record<string, any> | null {
  const src = fs.readFileSync(file, 'utf8');
  const m = src.match(/export const metadata[^=]*=\s*\{/);
  if (!m) return null;
  const start = m.index! + m[0].length - 1; // index of the opening '{'
  let depth = 0;
  let end = -1;
  for (let i = start; i < src.length; i++) {
    const c = src[i];
    if (c === '{') depth++;
    else if (c === '}') {
      depth--;
      if (depth === 0) {
        end = i;
        break;
      }
    }
  }
  if (end === -1) return null;
  const objText = src.slice(start, end + 1);
  // Always define siteUrl in the eval scope (the slice starts at `metadata`,
  // so any `const siteUrl` declared above is OUT of scope here).
  const code = `const siteUrl = '${SITE}';\nconst metadata = ${objText};\nreturn metadata;`;
  try {
    return new Function('process', code)(process) as Record<string, any>;
  } catch (e) {
    console.warn(`  ⚠️  skip ${file}: metadata eval failed (${(e as Error).message})`);
    return null;
  }
}

function counterpartSlug(meta: Record<string, any>, locale: BlogLocale): string | undefined {
  const langs = meta.alternates?.languages ?? {};
  const raw = locale === 'en' ? langs.fr : langs.en;
  if (!raw) return undefined;
  // Legacy alternates store FULL urls (e.g. https://site/fr/blog/slug).
  const pathname = (() => {
    try {
      return new URL(raw, SITE).pathname;
    } catch {
      return raw;
    }
  })();
  return pathname.replace(/^\/(fr\/)?blog\//, '').replace(/^\//, '').replace(/\/$/, '');
}

function ogPath(meta: Record<string, any>): string {
  const img = meta.openGraph?.images?.[0];
  const url = typeof img === 'string' ? img : img?.url;
  if (!url) return '';
  try {
    return new URL(url, SITE).pathname;
  } catch {
    return String(url).replace(/^\/+/, '/');
  }
}

function main() {
  const posts: BlogPostLite[] = [];
  for (const { dir, locale } of ROOTS) {
    if (!fs.existsSync(dir)) continue;
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      if (entry.name === '[slug]') continue;
      const file = path.join(dir, entry.name, 'page.tsx');
      if (!fs.existsSync(file)) continue;
      const meta = getMetadata(file);
      if (!meta) continue;
      const slug = entry.name;
      const frSlug = counterpartSlug(meta, locale);
      const published = meta.other?.datePublished || '';
      posts.push({
        slug,
        locale,
        title: typeof meta.title === 'string' ? meta.title : String(meta.title ?? ''),
        description: meta.description || '',
        frSlug,
        ogImage: ogPath(meta),
        published,
        modified: meta.other?.dateModified || published,
      });
    }
  }

  const out = `// AUTO-GENERATED by scripts/sync-legacy.ts — do not edit manually.
// Bodies of legacy articles live in their original page.tsx; this mirrors
// only their SEO metadata so sitemap + audit cover every article.
import type { BlogPostLite } from '../lib/content/types';

export const legacyPosts: BlogPostLite[] = ${JSON.stringify(posts, null, 2)};
`;
  fs.writeFileSync(path.resolve('src/content/legacy.ts'), out);
  console.log(`✅ legacy.ts: ${posts.length} legacy posts synced (en/fr combined).`);
}

main();
