// Auto-register blog content files into src/content/blog/index.ts.
// Agents NEVER edit index.ts by hand: create src/content/blog/<slug>.ts
// exporting `post`, then run `npm run blog:sync`.
import fs from 'fs';
import path from 'path';
import type { BlogPost } from '../src/lib/content/types';

const DIR = path.resolve(process.cwd(), 'src/content/blog');
const INDEX = path.join(DIR, 'index.ts');

function toIdent(slug: string): string {
  const id = slug
    .replace(/[^a-zA-Z0-9]+/g, ' ')
    .trim()
    .split(' ')
    .map((w, i) => (i === 0 ? w.charAt(0).toLowerCase() + w.slice(1) : w.charAt(0).toUpperCase() + w.slice(1)))
    .join('');
  return /^[a-zA-Z]/.test(id) ? id : `p${id}`;
}

async function loadPosts(): Promise<BlogPost[]> {
  const files = fs.readdirSync(DIR).filter((f) => f.endsWith('.ts') && f !== 'index.ts');
  const posts: BlogPost[] = [];
  for (const f of files) {
    const mod = await import(path.join(DIR, f));
    if (mod && (mod as { post?: BlogPost }).post) posts.push((mod as { post: BlogPost }).post);
  }
  return posts.sort((a, b) => a.slug.localeCompare(b.slug));
}

function render(posts: BlogPost[]): string {
  const imports = posts.map((p) => `import { post as ${toIdent(p.slug)} } from './${p.slug}';`).join('\n');
  const arr = posts.map((p) => `  ${toIdent(p.slug)},`).join('\n');
  return `// AUTO-GENERATED by scripts/sync-blog.ts — do not edit by hand.
// Add an article: create src/content/blog/<slug>.ts exporting \`post\`, then run \`npm run blog:sync\`.
import type { BlogPost } from '@/lib/content/types';

${imports}

export const allPosts: BlogPost[] = [
${arr}
];

export function getPost(slug: string, locale: BlogPost['locale']): BlogPost | undefined {
  return allPosts.find((p) => p.slug === slug && p.locale === locale);
}
`;
}

async function main() {
  const posts = await loadPosts();
  fs.writeFileSync(INDEX, render(posts));
  console.log(`Synced ${posts.length} posts -> src/content/blog/index.ts`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
